Use analyzer input and output
konveyor-ecosystem/kantra pull request #17
Opened 2023-08-10 01:15 UTC by eemcmullan

2023-08-11 20:09 UTC, pranavgaikwad requested changes

2023-08-11 20:09 UTC, pranavgaikwad commented on cmd/analyze.go
> +func (a *analyzeCommand) Run(ctx context.Context) error {
Run() will always execute even when I am using `--list-sources` right? we probably dont want that?

2023-08-11 20:09 UTC, pranavgaikwad commented on cmd/settings.go
> +	SourceRepoPath         = "/opt/example"
why not re-use InputPath for all inputs? you will only run one command at a time, so shouldn't be an issue

2023-08-11 20:09 UTC, pranavgaikwad commented on settings.json
> +[
should create provider settings using only the API. this quickly becomes stale when there's a change in the config

2023-08-11 21:06 UTC, eemcmullan commented on cmd/analyze.go
> +func (a *analyzeCommand) Run(ctx context.Context) error {
Good point. Will update

2023-08-11 21:10 UTC, eemcmullan commented on settings.json
> +[
Makes sense. Will update

2023-08-14 18:43 UTC, pranavgaikwad approved these changes
think `ouput.yaml` typo needs fixing, other than that, feel free to address in follow up. Great PR! Thank you!

2023-08-14 18:43 UTC, pranavgaikwad commented on cmd/analyze.go
> +	fp := filepath.Join(trimmedOutput, "outout.yaml")
```suggestion
	fp := filepath.Join(trimmedOutput, "output.yaml")
```

2023-08-14 18:43 UTC, pranavgaikwad commented on cmd/analyze.go
> +	trimmedOutput := strings.TrimRight(a.output, "/")
this is redundant, Join() takes care of everything

2023-08-14 18:43 UTC, pranavgaikwad commented on cmd/analyze.go
> +	analyzeCommand.Flags().StringVar(&analyzeCmd.rules, "rules", "", "Rules for analysis")
I think this should be an StringArray() variable, but fine for now

2023-08-14 18:53 UTC, eemcmullan commented on cmd/analyze.go
> +	analyzeCommand.Flags().StringVar(&analyzeCmd.rules, "rules", "", "Rules for analysis")
created issue to address shortly

2023-08-14 18:59 UTC, merged